// This file was generated by scripts/generate-asset-icons.ts
// Do not edit manually.

// Manual export for wrapper component
export { AssetIcon, type AssetIconProps } from './AssetIcon';

export { AAVEAssetIcon } from './AAVEAssetIcon';
export { AQUAAssetIcon } from './AQUAAssetIcon';
export { AVAXAssetIcon } from './AVAXAssetIcon';
export { BLNDAssetIcon } from './BLNDAssetIcon';
export { BNBAssetIcon } from './BNBAssetIcon';
export { BitcoinAssetIcon } from './BitcoinAssetIcon';
export { BitcoinCashAssetIcon } from './BitcoinCashAssetIcon';
export { COMPAssetIcon } from './COMPAssetIcon';
export { DaiAssetIcon } from './DaiAssetIcon';
export { EthereumAssetIcon } from './EthereumAssetIcon';
export { FUSDAssetIcon } from './FUSDAssetIcon';
export { HAPIAssetIcon } from './HAPIAssetIcon';
export { LINKAssetIcon } from './LINKAssetIcon';
export { MATICAssetIcon } from './MATICAssetIcon';
export { SHIBAssetIcon } from './SHIBAssetIcon';
export { SOLAssetIcon } from './SOLAssetIcon';
export { SUSHIAssetIcon } from './SUSHIAssetIcon';
export { SmartBCHAssetIcon } from './SmartBCHAssetIcon';
export { StellarAssetIcon } from './StellarAssetIcon';
export { UNIAssetIcon } from './UNIAssetIcon';
export { USDcAssetIcon } from './USDcAssetIcon';
export { USDtAssetIcon } from './USDtAssetIcon';
export { VerseXAssetIcon } from './VerseXAssetIcon';
export { VerseAssetIcon } from './VerseAssetIcon';
export { YFIAssetIcon } from './YFIAssetIcon';
export { ZanoAssetIcon } from './ZanoAssetIcon';
export { TBTCAssetIcon } from './TBTCAssetIcon';
export { WBTCAssetIcon } from './WBTCAssetIcon';

