#!/usr/bin/env tsx
import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ICONS_DIR = join(__dirname, '../src/icons');
const OUTPUT_FILE = join(__dirname, '../src/components/icon/iconMap.ts');

// Read all SVG files from src/icons
const svgFiles = readdirSync(ICONS_DIR).filter(file => file.endsWith('.svg'));

console.log(`Found ${svgFiles.length} icon files`);

// Generate the icon map
const iconEntries = svgFiles.map(file => {
  const iconName = file
    .replace('.svg', '')
    .toLowerCase()
    .replace(/\s+/g, '-');
  const svgContent = readFileSync(join(ICONS_DIR, file), 'utf-8');
  
  // Extract viewBox and paths from SVG
  const viewBoxMatch = svgContent.match(/viewBox="([^"]+)"/);
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24';
  
  // Extract all content between <svg> tags
  const contentMatch = svgContent.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  const content = contentMatch ? contentMatch[1].trim() : '';
  
  // Replace hardcoded colors with currentColor
  let processedContent = content
    .replace(/fill="(?!none)[^"]*"/g, 'fill="currentColor"')
    .replace(/stroke="(?!none)[^"]*"/g, 'stroke="currentColor"')
    .replace(/stroke-width/g, 'strokeWidth')
    .replace(/stroke-linecap/g, 'strokeLinecap')
    .replace(/stroke-linejoin/g, 'strokeLinejoin')
    .replace(/fill-rule/g, 'fillRule')
    .replace(/clip-rule/g, 'clipRule');
  
  return {
    name: iconName,
    viewBox,
    content: processedContent
  };
});

// Generate TypeScript file
const tsContent = `// This file was generated by scripts/generate-icon-map.ts
// Do not edit manually.

export interface IconData {
  viewBox: string;
  content: string;
}

export const iconMap: Record<string, IconData> = {
${iconEntries.map(({ name, viewBox, content }) => {
  // Escape content for template literal
  const escapedContent = content.replace(/`/g, '\\`').replace(/\$/g, '\\$');
  return `  '${name}': {
    viewBox: '${viewBox}',
    content: \`${escapedContent}\`
  }`;
}).join(',\n')}
};

export const iconNames = Object.keys(iconMap) as Array<keyof typeof iconMap>;
`;

writeFileSync(OUTPUT_FILE, tsContent, 'utf-8');
console.log(`✅ Generated icon map at ${OUTPUT_FILE}`);
console.log(`📦 ${iconEntries.length} icons exported`);

