import { transform } from '@svgr/core';
import camelcase from 'camelcase';
import { readdir, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const projectRoot = path.resolve(process.cwd());
const svgSourceDir = path.resolve(projectRoot, 'src', 'icons');
const iconsOutputDir = path.resolve(projectRoot, 'src', 'components', 'icons');

const HEADER = [
  '// This file was generated by scripts/generate-icons.ts',
  '// Do not edit manually.'
].join('\n');

async function generateIcons() {
  await mkdir(iconsOutputDir, { recursive: true });

  const existing = await readdir(iconsOutputDir);
  await Promise.all(
    existing
      .filter(
        (file) =>
          file.toLowerCase().endsWith('.tsx') &&
          !file.toLowerCase().endsWith('.stories.tsx')
      )
      .map((file) => rm(path.join(iconsOutputDir, file)))
  );

  const files = await readdir(svgSourceDir);
  const svgFiles = files.filter((file) => file.toLowerCase().endsWith('.svg'));

  if (svgFiles.length === 0) {
    console.warn('[icons] No SVG files found in src/icons.');
    return;
  }

  const exportLines: string[] = [HEADER];

  for (const file of svgFiles) {
    const filePath = path.join(svgSourceDir, file);
    const svgCode = await readFile(filePath, 'utf8');
    const baseName = path.basename(file, path.extname(file));
    const cleanedName = baseName
      .replace(/^(icon[\-_]?)/i, '')
      .replace(/([\-_]?icon)$/i, '')
      .replace(/\s+/g, '-');
    let componentBaseName = camelcase(cleanedName, {
      pascalCase: true,
      preserveConsecutiveUppercase: true
    }).replace(/[^A-Za-z0-9]/g, '');
    if (!componentBaseName) {
      componentBaseName = 'Icon';
    }
    if (/^[0-9]/.test(componentBaseName)) {
      componentBaseName = `Icon${componentBaseName}`;
    }
    const componentName = `${componentBaseName}Icon`;

    let componentCode = await transform(
      svgCode,
      {
        icon: true,
        typescript: true,
        prettier: false,
        memo: false,
        jsxRuntime: 'automatic',
        exportType: 'named',
        namedExport: componentName,
        plugins: ['@svgr/plugin-svgo', '@svgr/plugin-jsx'],
        svgoConfig: {
          plugins: [
            {
              name: 'removeAttrs',
              params: { attrs: '(data-name|fill-rule|clip-rule)' }
            },
            {
              name: 'convertColors',
              params: { currentColor: true }
            }
          ]
        }
      },
      { componentName }
    );

    componentCode = componentCode.replace(/fill="[^"]*"/g, 'fill="currentColor"');
    if (!componentCode.includes(HEADER)) {
      componentCode = `${HEADER}\n${componentCode}`;
    }
    componentCode = componentCode.replace(
      new RegExp(`export const ${componentName} =`),
      `export const ${componentName} =`
    );
    componentCode += `\n${componentName}.displayName = '${componentName}';\n`;

    const outputPath = path.join(iconsOutputDir, `${componentName}.tsx`);
    await writeFile(outputPath, componentCode, 'utf8');
    exportLines.push(`export { ${componentName} } from './${componentName}';`);
  }

  exportLines.push('');

  const indexPath = path.join(iconsOutputDir, 'index.ts');
  await writeFile(indexPath, `${exportLines.join('\n')}\n`, 'utf8');

  console.info(`[icons] Generated ${svgFiles.length} icon components.`);
}

await generateIcons();


