// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const ArrowLeftIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M18 9.33V14.67C18 17.99 15.65 19.34 12.78 17.69L11.5 16.95C11.19 16.77 11 16.44 11 16.08V7.92C11 7.56 11.19 7.23 11.5 7.05L12.78 6.31C15.65 4.66 18 6.01 18 9.33Z" fill="currentColor" /><path d="M10 8.79V15.22C10 15.61 9.58 15.85 9.25 15.65L8.15 15.01C5.28 13.36 5.28 10.64 8.15 8.99L9.25 8.35C9.58 8.16 10 8.4 10 8.79Z" fill="currentColor" /></svg>;
export { ArrowLeftIcon };
ArrowLeftIcon.displayName = 'ArrowLeftIcon';
