// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const ArrowRight2Icon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M15.2 10.49L13.23 8.52L10.02 5.31C9.33999 4.64 8.17999 5.12 8.17999 6.08V12.31V17.92C8.17999 18.88 9.33999 19.36 10.02 18.68L15.2 13.5C16.03 12.68 16.03 11.32 15.2 10.49Z" fill="currentColor" /></svg>;
export { ArrowRight2Icon };
ArrowRight2Icon.displayName = 'ArrowRight2Icon';
