// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const ArrowUp1Icon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M18.68 13.98L15.47 10.77L13.51 8.80001C12.68 7.97001 11.33 7.97001 10.5 8.80001L5.32001 13.98C4.64001 14.66 5.13001 15.82 6.08001 15.82H11.69H17.92C18.88 15.82 19.36 14.66 18.68 13.98Z" fill="currentColor" /></svg>;
export { ArrowUp1Icon };
ArrowUp1Icon.displayName = 'ArrowUp1Icon';
