// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const BoltIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M15.9509 0.0608971C16.2364 0.192426 16.3903 0.50633 16.3196 0.812611L14.3626 9.27955H19.3502C19.6005 9.27955 19.8295 9.4205 19.9423 9.64398C20.055 9.86746 20.0324 10.1354 19.8836 10.3368L9.99135 23.7307C9.80631 23.9813 9.47185 24.0693 9.18745 23.9423C8.90304 23.8153 8.74535 23.5075 8.8084 23.2025L10.5257 14.8955H5.64978C5.39945 14.8955 5.17044 14.7546 5.05767 14.5311C4.94491 14.3076 4.9676 14.0396 5.11634 13.8383L15.1399 0.269202C15.3267 0.0163536 15.6654 -0.0706313 15.9509 0.0608971Z" fill="currentColor" /></svg>;
export { BoltIcon };
BoltIcon.displayName = 'BoltIcon';
