// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const BrokenStreakIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M10 21L12 22L15 13L11.7182 13.7928L17 2.5C14 2.5 13 3.5 11.7182 5.72461C10.9235 3.57554 9.37691 2 6.43649 2C2.42015 2 0.87353 5.63232 1.00802 9.60743C1.22809 16.1601 9.42131 20.7107 10 21Z" fill="currentColor" /><path d="M22.6408 10.4472C22.6408 7.75912 22.4878 4.54163 19 3.5L15.5 11H17.5L14.5 21C17.6772 19.0803 22.6408 13.1353 22.6408 10.4472Z" fill="currentColor" /></svg>;
export { BrokenStreakIcon };
BrokenStreakIcon.displayName = 'BrokenStreakIcon';
