// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const CheckmarkIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M19.2446 4.6694C20.1038 3.81023 21.4965 3.81023 22.3556 4.6694C23.2148 5.52857 23.2148 6.92122 22.3556 7.78038L10.8054 19.3306C9.94628 20.1897 8.55363 20.1897 7.69447 19.3306L1.64437 13.2805C0.785208 12.4213 0.785208 11.0286 1.64437 10.1695C2.44988 9.36398 3.72474 9.31313 4.58885 10.018L4.75536 10.1695L9.24996 14.6641L19.2446 4.6694Z" fill="currentColor" /></svg>;
export { CheckmarkIcon };
CheckmarkIcon.displayName = 'CheckmarkIcon';
