// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const ChevronRightIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M9.29829 21.4518L16.1437 14.8197C17.4754 13.5039 18.1412 12.8459 18.153 12.0274C18.1533 12.0077 18.1533 11.9879 18.153 11.9681C18.1405 11.1496 17.4745 10.4927 16.1425 9.17878C13.3517 6.43744 11.468 4.61899 10.3061 3.50981L9.26982 2.52714C8.50622 1.80882 7.3065 1.82965 6.56706 2.55888C5.81383 3.30224 5.81187 4.50457 6.55592 5.25176L13.2788 12.0011C10.4995 14.7516 8.65624 16.6089 7.53153 17.7543L6.53487 18.776C5.8065 19.5288 5.82768 20.7118 6.56706 21.4408C7.32093 22.1837 8.54033 22.1854 9.29829 21.4518Z" fill="currentColor" /></svg>;
export { ChevronRightIcon };
ChevronRightIcon.displayName = 'ChevronRightIcon';
