// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const DeclinedIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M23 12C23 18.0751 18.0751 23 12 23C5.92487 23 0.999999 18.0751 1 12C1 5.92487 5.92487 0.999999 12 1C18.0751 1 23 5.92487 23 12ZM18.6504 12C18.6504 11.1083 17.9355 10.3816 17.0439 10.3701C16.242 10.3599 16.8129 10.3701 16.0547 10.3701C15.2964 10.3701 7.80795 10.3599 7.00586 10.3701C6.11439 10.3817 5.40039 11.1084 5.40039 12C5.40039 12.8916 6.11439 13.6183 7.00586 13.6299C7.80795 13.6401 15.5855 13.6299 16.3437 13.6299C17.1019 13.6299 16.242 13.6401 17.0439 13.6299C17.9355 13.6184 18.6504 12.8917 18.6504 12Z" fill="currentColor" /></svg>;
export { DeclinedIcon };
DeclinedIcon.displayName = 'DeclinedIcon';
