// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const DiamondsIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M21.77 9.80002L20.97 8.00002L19.21 4.04002C18.74 3.00002 18 2.15002 16.3 2.15002H7.70001C6.00001 2.15002 5.26001 3.00002 4.79001 4.04002L3.03001 8.00002L2.23001 9.80002C1.77001 10.85 2.02001 12.39 2.79001 13.24L9.64001 20.78C10.94 22.21 13.06 22.21 14.36 20.78L21.21 13.24C21.98 12.39 22.23 10.85 21.77 9.80002Z" fill="currentColor" /></svg>;
export { DiamondsIcon };
DiamondsIcon.displayName = 'DiamondsIcon';
