// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const EoseosIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M9.28 20.31C9.45 20.79 8.92999 21.23 8.48999 20.97L5.34 19.18C4.77 18.85 4.42001 18.06 4.54001 17.42L5.48001 12.75C5.59001 12.2 6.35001 12.15 6.54001 12.67L9.28 20.31Z" fill="currentColor" /><path d="M18.66 19.18L15.5 20.98C15.06 21.23 14.54 20.8 14.71 20.32L17.46 12.61C17.65 12.09 18.41 12.14 18.52 12.69L19.47 17.42C19.58 18.06 19.23 18.85 18.66 19.18Z" fill="currentColor" /><path d="M17.08 7.31995C17.32 7.61995 17.39 8.01995 17.26 8.37995L12.52 21.6299C12.35 22.1199 11.66 22.1199 11.49 21.6299L6.74999 8.38995C6.61999 8.02995 6.68999 7.62995 6.92999 7.32995L10.75 2.62995C11.44 1.79995 12.58 1.79995 13.28 2.62995L17.08 7.31995Z" fill="currentColor" /></svg>;
export { EoseosIcon };
EoseosIcon.displayName = 'EoseosIcon';
