// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const GrammerlyIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M19.11 4.96C15.2 1.05 8.85003 1.05 4.94003 4.96C0.960027 8.94 1.03003 15.43 5.14003 19.33C8.94003 22.92 15.1 22.92 18.9 19.33C23.02 15.43 23.09 8.94 19.11 4.96ZM16.38 16.65C15.18 17.79 13.6 18.36 12.02 18.36C10.44 18.36 8.86003 17.79 7.66003 16.65C7.36003 16.36 7.35003 15.89 7.63003 15.59C7.92003 15.29 8.39003 15.28 8.69003 15.56C10.52 17.29 13.51 17.3 15.35 15.56C15.65 15.28 16.13 15.29 16.41 15.59C16.7 15.89 16.68 16.36 16.38 16.65Z" fill="currentColor" /></svg>;
export { GrammerlyIcon };
GrammerlyIcon.displayName = 'GrammerlyIcon';
