// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const LampIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M12.5 5.48003C12.58 5.48003 12.66 5.48003 12.75 5.49003V2.53003C12.75 2.12003 12.41 1.78003 12 1.78003C11.59 1.78003 11.25 2.12003 11.25 2.53003V5.49003C11.33 5.48003 11.41 5.48003 11.5 5.48003C6.88997 5.71003 3.21997 9.51003 3.21997 14.18V16.12C3.21997 17.22 4.11997 18.12 5.21997 18.12H18.78C19.88 18.12 20.78 17.22 20.78 16.12V14.18C20.78 9.51003 17.11 5.71003 12.5 5.48003Z" fill="currentColor" /><path d="M14.73 19.11C15.06 19.11 15.3 19.42 15.22 19.74C14.84 21.17 13.54 22.22 12 22.22C10.46 22.22 9.16001 21.17 8.78001 19.74C8.70001 19.42 8.94001 19.11 9.27001 19.11H14.73Z" fill="currentColor" /></svg>;
export { LampIcon };
LampIcon.displayName = 'LampIcon';
