// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const MoreAlternativeIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M14.5 3.5C14.5 4.88071 13.3807 6 12 6C10.6193 6 9.5 4.88071 9.5 3.5C9.5 2.11929 10.6193 1 12 1C13.3807 1 14.5 2.11929 14.5 3.5Z" fill="currentColor" /><path d="M14.5 12C14.5 13.3807 13.3807 14.5 12 14.5C10.6193 14.5 9.5 13.3807 9.5 12C9.5 10.6193 10.6193 9.5 12 9.5C13.3807 9.5 14.5 10.6193 14.5 12Z" fill="currentColor" /><path d="M14.5 20.5C14.5 21.8807 13.3807 23 12 23C10.6193 23 9.5 21.8807 9.5 20.5C9.5 19.1193 10.6193 18 12 18C13.3807 18 14.5 19.1193 14.5 20.5Z" fill="currentColor" /></svg>;
export { MoreAlternativeIcon };
MoreAlternativeIcon.displayName = 'MoreAlternativeIcon';
