// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const ProfileRemoveIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M12 2C9.38 2 7.25 4.13 7.25 6.75C7.25 9.32 9.26 11.4 11.88 11.49C11.96 11.48 12.04 11.48 12.1 11.49C12.12 11.49 12.13 11.49 12.15 11.49C12.16 11.49 12.16 11.49 12.17 11.49C14.73 11.4 16.74 9.32 16.75 6.75C16.75 4.13 14.62 2 12 2Z" fill="currentColor" /><path d="M17.08 14.16C14.29 12.3 9.74002 12.3 6.93002 14.16C5.66002 15 4.96002 16.15 4.96002 17.38C4.96002 18.61 5.66002 19.75 6.92002 20.59C8.32002 21.53 10.16 22 12 22C13.84 22 15.68 21.53 17.08 20.59C18.34 19.74 19.04 18.6 19.04 17.36C19.03 16.14 18.34 14.99 17.08 14.16ZM13.83 18.07H10.18C9.80002 18.07 9.49002 17.76 9.49002 17.38C9.49002 17 9.80002 16.69 10.18 16.69H13.83C14.21 16.69 14.52 17 14.52 17.38C14.52 17.76 14.21 18.07 13.83 18.07Z" fill="currentColor" /></svg>;
export { ProfileRemoveIcon };
ProfileRemoveIcon.displayName = 'ProfileRemoveIcon';
