// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const RightArrowIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M14.0891 4.64066C14.6749 4.05488 15.6254 4.05488 16.2112 4.64066L22.51 10.9395C23.0956 11.5253 23.0957 12.4758 22.51 13.0616L16.2112 19.3604C15.6255 19.9461 14.6749 19.946 14.0891 19.3604C13.5037 18.7746 13.5036 17.825 14.0891 17.2393L17.8284 13.5H2.55103C1.72269 13.4999 1.05103 12.8284 1.05103 12C1.0512 11.1718 1.72279 10.5001 2.55103 10.5H17.8284L14.0891 6.76176C13.5036 6.17603 13.5036 5.22639 14.0891 4.64066Z" fill="currentColor" /></svg>;
export { RightArrowIcon };
RightArrowIcon.displayName = 'RightArrowIcon';
