// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const SendIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M1 10.7366C1 9.15959 2.5836 8.14535 4.0687 7.61495L19.4717 2.11387C20.9728 1.57776 22.4222 3.02716 21.8861 4.52825L16.3844 19.933C15.8552 21.4148 14.8369 23 13.2634 23C11.6821 23 10.6321 21.4385 10.0228 19.9793L9.30162 18.2519C8.97538 17.4705 9.13334 16.5707 9.70623 15.9472L19.3175 5.48629C19.5159 5.27038 19.5088 4.93647 19.3015 4.72914C19.077 4.50463 18.7155 4.49687 18.4815 4.71153L8.06133 14.2733C7.42806 14.8544 6.51491 15.0147 5.72155 14.6841L4.02303 13.9763C2.56043 13.3668 1 12.3211 1 10.7366Z" fill="currentColor" /></svg>;
export { SendIcon };
SendIcon.displayName = 'SendIcon';
