// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const Share1Icon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><g clipPath="url(#clip0_18003_7207)"><path d="M23.6153 11.6453C23.9473 11.3299 23.9473 10.8007 23.6153 10.4853L16.2435 3.48206C15.7339 2.99795 14.8925 3.35918 14.8925 4.06206V6.56651C14.8925 6.96676 14.5943 7.3041 14.1996 7.37018C7.02133 8.57184 3.14375 12.8693 1.2437 17.7485C0.933187 18.5459 2.02776 19.127 2.67965 18.5726C5.59423 16.0943 9.30992 14.8699 14.0914 14.7486C14.5331 14.7374 14.8925 15.0968 14.8925 15.5386V18.0685C14.8925 18.7714 15.7339 19.1326 16.2435 18.6485L23.6153 11.6453Z" fill="currentColor" /></g><defs><clipPath id="clip0_18003_7207"><rect width={24} height={24} fill="currentColor" /></clipPath></defs></svg>;
export { Share1Icon };
Share1Icon.displayName = 'Share1Icon';
