// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const TetherusdtIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M21.71 9.89999L19.31 5.07999C18.84 4.12999 17.59 3.35999 16.53 3.35999H7.46998C6.40998 3.35999 5.15998 4.12999 4.68998 5.07999L2.28997 9.89999C1.70997 11.06 2.02997 12.71 2.97997 13.58L9.90998 19.87C11.06 20.91 12.93 20.91 14.08 19.87L21.01 13.58C21.97 12.71 22.29 11.05 21.71 9.89999ZM16 9.24999H12.75V14.5C12.75 14.91 12.41 15.25 12 15.25C11.59 15.25 11.25 14.91 11.25 14.5V9.24999H7.99998C7.58998 9.24999 7.24998 8.90999 7.24998 8.49999C7.24998 8.08999 7.58998 7.74999 7.99998 7.74999H16C16.41 7.74999 16.75 8.08999 16.75 8.49999C16.75 8.90999 16.41 9.24999 16 9.24999Z" fill="currentColor" /></svg>;
export { TetherusdtIcon };
TetherusdtIcon.displayName = 'TetherusdtIcon';
