// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const UnsaveIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M7.18036 3H16.82C18.2967 3 19.5202 4.13448 19.6735 5.57324L19.6901 5.86426V19.9502C19.6901 20.6363 19.4541 20.8754 19.3405 20.9424C19.2275 21.0089 18.9049 21.1 18.3063 20.7666L18.3054 20.7656L13.4255 18.0557H13.4245C12.983 17.8075 12.4676 17.7129 12.0085 17.7129C11.5457 17.7129 11.0285 17.8086 10.5847 18.0557L5.7077 20.7637C5.11007 21.0927 4.78564 21.0029 4.66962 20.9346C4.55428 20.8665 4.32005 20.6285 4.32001 19.9502V5.86035C4.32001 4.29095 5.60433 3 7.18036 3Z" stroke="currentColor" strokeWidth={2} /></svg>;
export { UnsaveIcon };
UnsaveIcon.displayName = 'UnsaveIcon';
