// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const VelasvlxIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M21 3.15002H3C2.59 3.15002 2.25 3.49002 2.25 3.90002C2.25 4.31002 2.59 4.65002 3 4.65002H21C21.41 4.65002 21.75 4.31002 21.75 3.90002C21.75 3.49002 21.41 3.15002 21 3.15002Z" fill="currentColor" /><path d="M4.04002 6.23999H19.97C20.85 6.23999 21.38 7.20999 20.9 7.94999L12.94 20.34C12.5 21.02 11.51 21.02 11.07 20.34L3.11 7.94999C2.63 7.20999 3.16002 6.23999 4.04002 6.23999Z" fill="currentColor" /></svg>;
export { VelasvlxIcon };
VelasvlxIcon.displayName = 'VelasvlxIcon';
