// This file was generated by scripts/generate-icons.ts
// Do not edit manually.
import type { SVGProps } from "react";
const VolumeLow1Icon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M19.33 16.75C19.17 16.75 19.02 16.7 18.88 16.6C18.55 16.35 18.48 15.88 18.73 15.55C20.3 13.46 20.3 10.54 18.73 8.45C18.48 8.12 18.55 7.65 18.88 7.4C19.21 7.15 19.68 7.22 19.93 7.55C21.9 10.17 21.9 13.83 19.93 16.45C19.79 16.65 19.56 16.75 19.33 16.75Z" fill="currentColor" /><path d="M15.35 3.78C14.23 3.16 12.8 3.32 11.34 4.23L8.42002 6.06C8.22002 6.18 7.99002 6.25 7.76002 6.25H6.83002H6.33002C3.91002 6.25 2.58002 7.58 2.58002 10V14C2.58002 16.42 3.91002 17.75 6.33002 17.75H6.83002H7.76002C7.99002 17.75 8.22002 17.82 8.42002 17.94L11.34 19.77C12.22 20.32 13.08 20.59 13.88 20.59C14.4 20.59 14.9 20.47 15.35 20.22C16.46 19.6 17.08 18.31 17.08 16.59V7.41C17.08 5.69 16.46 4.4 15.35 3.78Z" fill="currentColor" /></svg>;
export { VolumeLow1Icon };
VolumeLow1Icon.displayName = 'VolumeLow1Icon';
